`timescale 1ns / 1ps
`include "_parameter.v"

// ============================================================================
// ITMN_TB_V2 — End-to-end multi-sample testbench for ITM_Top_v3.
//
// Drives the v3 controller through encoder + 5 ITM blocks + GAP + FC for N
// samples from the SUPER test set.  Per sample prints predicted class +
// expected logits diff.  Final summary: HW-vs-Python-golden match rate.
//
// Golden files (generated by itmn_pipeline.py extract + extract_multi.py):
//   golden_all/encoder/Encoder_{Weight_Fused,Bias_Fused}.txt
//   golden_all/gap_fc/FC_{Weight,Bias}.txt
//   golden_all/multi/all_waves.txt        (N × 12000 entries, 4 hex chars each)
//   golden_all/multi/all_logits.txt       (N × 5 entries)
//   golden_all/block_{00..04}_layer{00,01,03,04,06}/{P1_*, W_*, Mam_*, Inc_*}
//
// Run from ITMN_RTL_srcs root with:
//   xsim/vivado xrun -L work ITM_CTRL_TB_v2.v
//
// Configure NUM_SAMPLES via the parameter below (default 100).  Each sample
// takes ~30M sim cycles (block 4 dominates) so 100 samples → many hours of
// xsim.  For faster smoke tests, override to 1-10.
// ============================================================================
module ITMN_TB_v2;

    // ----------------------------------------------------------------
    // Run configuration
    // ----------------------------------------------------------------
    parameter integer NUM_SAMPLES = 100;
    parameter integer MAX_CYCLES  = 200_000_000;   // generous timeout per block

    // ----------------------------------------------------------------
    // Clock / reset
    // ----------------------------------------------------------------
    reg clk;
    reg rst;
    reg start;
    initial begin clk = 0; forever #5 clk = ~clk; end

    // ----------------------------------------------------------------
    // DUT ports
    // ----------------------------------------------------------------
    wire done_phase1, done_inception, done_mamba, done_all;
    wire done_encoder, done_gap, done_fc;
    wire signed [15:0] logit0, logit1, logit2, logit3, logit4;

    reg  dma_write_en;
    reg  [1:0]  dma_target;
    reg  [14:0] dma_addr;
    reg  [255:0] dma_wdata;
    wire dma_ready;

    reg  [9:0] BLK_T_REG;
    reg  [3:0] BLK_CH_IN_REG, BLK_CH_OUT_REG, BLK_CH_M_REG, BLK_DT_REG;
    reg        BLK_NEED_POOL_REG, BLK_CASCADE_REG;
    reg        BLK_ENC_MODE_REG, BLK_HEAD_MODE_REG;
    reg  [9:0] BLK_T_ENC_REG, BLK_T_GAP_REG;

    wire [255:0] dma_rdata_unused;

    ITM_Top_v3 uut (
        .clk(clk), .rst(rst), .start(start),
        .done_phase1(done_phase1), .done_inception(done_inception),
        .done_mamba(done_mamba), .done_all(done_all),
        .done_encoder(done_encoder), .done_gap(done_gap), .done_fc(done_fc),
        .T_MAX(BLK_T_REG),
        .CH_IN(BLK_CH_IN_REG), .CH_OUT(BLK_CH_OUT_REG),
        .CH_M(BLK_CH_M_REG),   .DT_RANK(BLK_DT_REG),
        .need_pool(BLK_NEED_POOL_REG), .cascade_mode(BLK_CASCADE_REG),
        .enc_mode(BLK_ENC_MODE_REG),   .head_mode(BLK_HEAD_MODE_REG),
        .T_ENC(BLK_T_ENC_REG),         .T_GAP(BLK_T_GAP_REG),
        .logit0(logit0), .logit1(logit1), .logit2(logit2),
        .logit3(logit3), .logit4(logit4),
        .dma_write_en(dma_write_en), .dma_target(dma_target),
        .dma_addr(dma_addr), .dma_wdata(dma_wdata),
        .dma_ready(dma_ready),
        .dma_read_en(1'b0), .dma_rtarget(2'd0), .dma_raddr(15'd0),
        .dma_rdata(dma_rdata_unused)
    );

    // ----------------------------------------------------------------
    // Memory map (mirror of ITM_CONTROLLER_v3.v localparams)
    // ----------------------------------------------------------------
    localparam A_INPUT_BASE  = 15'd0;
    localparam A_FINAL_OUT   = 15'd12000;
    localparam B_FINAL_OUT   = 15'd0;
    localparam B_ENC_IN_BASE = 15'd19000;
    localparam W_ENC_BASE    = 15'd14000;
    localparam W_FC_BASE     = 15'd14064;
    localparam C_P1_BIAS     = 15'd0;
    localparam C_INC_SCALE   = 15'd8;
    localparam C_INC_SHIFT   = 15'd16;
    localparam C_M_DW_BIAS   = 15'd24;
    localparam C_M_DT_BIAS   = 15'd40;
    localparam C_NORM_W      = 15'd56;
    localparam C_ENC_BIAS    = 15'd64;
    localparam C_FC_BIAS     = 15'd68;

    // ----------------------------------------------------------------
    // File-loaded arrays
    // ----------------------------------------------------------------
    // Encoder weights/bias (persistent across all samples)
    reg signed [15:0] f_EncW   [0:767];     // 64 × 12
    reg signed [15:0] f_EncB   [0:63];      // 64

    // FC weights/bias (persistent across all samples)
    reg signed [15:0] f_FcW    [0:639];     // 5 × 128
    reg signed [15:0] f_FcB    [0:4];       // 5

    // Per-block weights (re-$readmemh'd each block per sample; arrays sized for biggest block)
    reg signed [15:0] f_Wp1      [0:16383];
    reg signed [15:0] f_Bconv    [0:127];
    reg signed [15:0] f_Wbot     [0:4095];
    reg signed [15:0] f_Wb1      [0:4095];
    reg signed [15:0] f_Wb2      [0:9215];
    reg signed [15:0] f_Wb3      [0:19455];
    reg signed [15:0] f_Wb4      [0:39935];
    reg signed [15:0] f_Inc_Scale[0:127];
    reg signed [15:0] f_Inc_Shift[0:127];
    reg signed [15:0] f_Wmx      [0:32767];
    reg signed [15:0] f_Wmz      [0:32767];
    reg signed [15:0] f_Wconv    [0:1023];
    reg signed [15:0] f_Bconv_dw [0:255];
    reg signed [15:0] f_Wxproj   [0:12287];
    reg signed [15:0] f_Wdt      [0:2047];
    reg signed [15:0] f_Bdt      [0:255];
    reg signed [15:0] f_Alog     [0:4095];
    reg signed [15:0] f_Dparam   [0:255];
    reg signed [15:0] f_Woutproj [0:32767];
    reg signed [15:0] f_Norm_W   [0:127];

    // Multi-sample data (all_waves.txt is N × 12000 entries; layout per sample:
    //  for t in 0..999: for ch in 0..11: f_AllWaves[sample*12000 + t*12 + ch])
    // all_logits.txt is N × 5 entries.
    reg signed [15:0] f_AllWaves    [0:NUM_SAMPLES*12000-1];
    reg signed [15:0] f_AllLogits   [0:NUM_SAMPLES*5-1];
    reg        [15:0] f_AllPredFloat[0:NUM_SAMPLES-1];   // float-model argmax per sample

    // ----------------------------------------------------------------
    // Per-block param state
    // ----------------------------------------------------------------
    integer BLK_T, BLK_CH_IN, BLK_CH_OUT, BLK_CH_M, BLK_D_INNER, BLK_DT_RANK;
    integer BLK_DIM, BLK_BR_GRPS;
    integer DW_P1, DW_BOT, DW_B1, DW_B2, DW_B3, DW_B4, DW_MX, DW_MZ, DW_DW;
    integer DW_XPROJ, DW_DTPROJ, DW_ALOG, DW_DPARAM, DW_OUTPROJ;

    // ----------------------------------------------------------------
    // Loop / temp variables (all top-level for Verilog-2001)
    // ----------------------------------------------------------------
    integer i, t, c, k, c_grp, c_grp_m, c_grp_br, sample_idx, blk;
    integer lane;
    reg signed [15:0] exp_l0, exp_l1, exp_l2, exp_l3, exp_l4;
    reg signed [15:0] got_l0, got_l1, got_l2, got_l3, got_l4;
    integer match_cnt, total_samples;
    integer match_pred_hw_exp;        // count of pred_hw == pred_exp
    integer match_pred_hw_float;      // count of pred_hw == pred_float
    integer match_pred_exp_float;     // count of pred_exp == pred_float (sanity: should equal hw_float since hw=exp byte-exact)
    integer logit_match;
    integer pred_hw, pred_exp, pred_float;
    integer max_diff;
    integer cycle_blk;
    reg signed [15:0] max_v;

    // ================================================================
    // task dma_write
    // ================================================================
    task dma_write;
        input [1:0]  tgt;
        input [14:0] addr;
        input [255:0] data;
        begin
            @(negedge clk);
            dma_write_en = 1; dma_target = tgt;
            dma_addr = addr; dma_wdata = data;
            @(posedge clk); #1;
            dma_write_en = 0;
        end
    endtask

    // ================================================================
    // task set_block_params  (config + dynamic weight bases)
    // ================================================================
    task set_block_params;
        input integer bid;
        begin
            case (bid)
                0, 1: begin BLK_T=1000; BLK_CH_IN=4; BLK_CH_OUT=4; BLK_CH_M=8;  BLK_D_INNER=128; BLK_DT_RANK=4; end
                2, 3: begin BLK_T=500;  BLK_CH_IN=4; BLK_CH_OUT=4; BLK_CH_M=8;  BLK_D_INNER=128; BLK_DT_RANK=4; end
                4:    begin BLK_T=250;  BLK_CH_IN=4; BLK_CH_OUT=8; BLK_CH_M=16; BLK_D_INNER=256; BLK_DT_RANK=8; end
                default: begin BLK_T=1000; BLK_CH_IN=4; BLK_CH_OUT=4; BLK_CH_M=8; BLK_D_INNER=128; BLK_DT_RANK=4; end
            endcase
            BLK_T_REG      = BLK_T[9:0];
            BLK_CH_IN_REG  = BLK_CH_IN[3:0];
            BLK_CH_OUT_REG = BLK_CH_OUT[3:0];
            BLK_CH_M_REG   = (BLK_CH_M == 16) ? 4'd0 : BLK_CH_M[3:0];
            BLK_DT_REG     = BLK_DT_RANK[3:0];

            BLK_DIM     = BLK_CH_OUT * 4;
            BLK_BR_GRPS = (BLK_CH_OUT >= 8) ? 2 : 1;
            DW_P1     = 0;
            DW_BOT    = DW_P1  + BLK_CH_OUT * BLK_CH_IN * 16;
            DW_B1     = DW_BOT + BLK_BR_GRPS * BLK_CH_OUT * 16;
            DW_B2     = DW_B1  + BLK_BR_GRPS * BLK_CH_OUT * 16;
            DW_B3     = DW_B2  + BLK_BR_GRPS * 9  * BLK_DIM;
            DW_B4     = DW_B3  + BLK_BR_GRPS * 19 * BLK_DIM;
            DW_MX     = DW_B4  + BLK_BR_GRPS * 39 * BLK_DIM;
            DW_MZ     = DW_MX  + BLK_CH_M * BLK_CH_OUT * 16;
            DW_DW     = DW_MZ  + BLK_CH_M * BLK_CH_OUT * 16;
            DW_XPROJ  = DW_DW  + BLK_CH_M * 4;
            DW_DTPROJ = DW_XPROJ + 3 * BLK_D_INNER;
            DW_ALOG   = DW_DTPROJ + BLK_CH_M * BLK_DT_RANK;
            DW_DPARAM = DW_ALOG + BLK_CH_M * 16;
            DW_OUTPROJ= DW_DPARAM + BLK_CH_M;

            // Cascade / encode / head config per block (5-block ITMN super)
            //   blk 0 : encoder THEN block-0 chain, cascade copy 1→2 input (need_pool=0)
            //   blk 1 : cascade pool (T 1000 → 500)
            //   blk 2 : cascade copy
            //   blk 3 : cascade pool (T 500 → 250)
            //   blk 4 : terminal, head_mode=1 → GAP + FC → logits
            case (bid)
                0: begin
                    BLK_CASCADE_REG = 1'b1; BLK_NEED_POOL_REG = 1'b0;
                    BLK_ENC_MODE_REG = 1'b1; BLK_HEAD_MODE_REG = 1'b0;
                end
                1: begin
                    BLK_CASCADE_REG = 1'b1; BLK_NEED_POOL_REG = 1'b1;
                    BLK_ENC_MODE_REG = 1'b0; BLK_HEAD_MODE_REG = 1'b0;
                end
                2: begin
                    BLK_CASCADE_REG = 1'b1; BLK_NEED_POOL_REG = 1'b0;
                    BLK_ENC_MODE_REG = 1'b0; BLK_HEAD_MODE_REG = 1'b0;
                end
                3: begin
                    BLK_CASCADE_REG = 1'b1; BLK_NEED_POOL_REG = 1'b1;
                    BLK_ENC_MODE_REG = 1'b0; BLK_HEAD_MODE_REG = 1'b0;
                end
                4: begin
                    BLK_CASCADE_REG = 1'b0; BLK_NEED_POOL_REG = 1'b0;
                    BLK_ENC_MODE_REG = 1'b0; BLK_HEAD_MODE_REG = 1'b1;
                end
                default: begin
                    BLK_CASCADE_REG = 1'b0; BLK_NEED_POOL_REG = 1'b0;
                    BLK_ENC_MODE_REG = 1'b0; BLK_HEAD_MODE_REG = 1'b0;
                end
            endcase
            BLK_T_ENC_REG = 10'd1000;
            BLK_T_GAP_REG = 10'd250;
        end
    endtask

    // ================================================================
    // task load_encoder_and_fc_constants
    //   Persistent across all samples — load once at boot.
    //   Encoder weight @ ram_weight[14000..14063] : 64 words (one per output channel,
    //                                                12 lanes valid + 4 zero-pad)
    //   Encoder bias   @ ram_const [64..67]       : 4 words × 16 lanes = 64 channels
    //   FC weight      @ ram_weight[14064..14103] : 5 classes × 8 word/class
    //   FC bias        @ ram_const [68]           : 1 word, 5 lanes valid
    // ================================================================
    task load_encoder_and_fc_constants;
        integer cls, in_ch;
        begin
            // Encoder weights:
            //   Memory layout matches P1: at address (c_grp*16 + in_ch), the 16
            //   lanes hold W_enc[c_grp*16 + lane, in_ch] for lane = 0..15.
            //   c_grp ∈ 0..3 (64 output channels / 16 lanes), in_ch ∈ 0..11.
            //   f_EncW is shape (64, 12) row-major: f_EncW[out_ch*12 + in_ch].
            //   Total entries used: 4 c_grp × 12 in_ch = 48 of 64 reserved words
            //   (entries c_grp*16 + {12..15} are reserved but unread).
            for (c_grp = 0; c_grp < 4; c_grp = c_grp + 1)
                for (in_ch = 0; in_ch < 12; in_ch = in_ch + 1) begin
                    dma_wdata = 256'd0;
                    for (lane = 0; lane < 16; lane = lane + 1)
                        dma_wdata[lane*16 +: 16] = f_EncW[(c_grp*16 + lane)*12 + in_ch];
                    dma_write(2'd2, W_ENC_BASE + c_grp*16 + in_ch, dma_wdata);
                end
            // Encoder bias: 4 words × 16 lanes
            for (c = 0; c < 4; c = c + 1) begin
                dma_wdata = 256'd0;
                for (lane = 0; lane < 16; lane = lane + 1)
                    dma_wdata[lane*16 +: 16] = f_EncB[c*16 + lane];
                dma_write(2'd3, C_ENC_BIAS + c, dma_wdata);
            end
            // FC weights: 5 classes × 8 groups × 16 lanes
            for (cls = 0; cls < 5; cls = cls + 1)
                for (c_grp = 0; c_grp < 8; c_grp = c_grp + 1) begin
                    dma_wdata = 256'd0;
                    for (lane = 0; lane < 16; lane = lane + 1)
                        dma_wdata[lane*16 +: 16] = f_FcW[cls*128 + c_grp*16 + lane];
                    dma_write(2'd2, W_FC_BASE + cls*8 + c_grp, dma_wdata);
                end
            // FC bias: 5 lanes valid, 11 lanes zero
            dma_wdata = 256'd0;
            for (lane = 0; lane < 5; lane = lane + 1)
                dma_wdata[lane*16 +: 16] = f_FcB[lane];
            dma_write(2'd3, C_FC_BIAS, dma_wdata);
        end
    endtask

    // ================================================================
    // task load_waveform_sample
    //   Pull 12000 entries for sample N from f_AllWaves and DMA-write 1000
    //   words (12 lanes valid + 4 zero) to ram_b at B_ENC_IN_BASE.
    //   Order in f_AllWaves: sample*12000 + t*12 + ch  (matches extract_multi.py
    //   `for t in T: for ch in 12` loop).
    // ================================================================
    task load_waveform_sample;
        input integer sidx;
        begin
            for (t = 0; t < 1000; t = t + 1) begin
                dma_wdata = 256'd0;
                for (lane = 0; lane < 12; lane = lane + 1)
                    dma_wdata[lane*16 +: 16] = f_AllWaves[sidx*12000 + t*12 + lane];
                dma_write(2'd1, B_ENC_IN_BASE + t, dma_wdata);
            end
        end
    endtask

    // ================================================================
    // task load_block_weights
    //   Re-uses the canonical TB layout (matches itmn_pipeline extractor).
    //   Arrays f_* must already be $readmemh'd for the requested block.
    // ================================================================
    task load_block_weights;
        begin
            // -- P1 weight → W RAM
            for (c_grp = 0; c_grp < BLK_CH_OUT; c_grp = c_grp + 1)
                for (c = 0; c < BLK_CH_IN*16; c = c + 1) begin
                    for (i = 0; i < 16; i = i + 1)
                        dma_wdata[i*16 +: 16] = f_Wp1[(c_grp*16+i)*(BLK_CH_IN*16)+c];
                    dma_write(2'd2, DW_P1 + c_grp*(BLK_CH_IN*16) + c, dma_wdata);
                end

            // -- P1 bias + Inc BN scale/shift → Const RAM
            for (c_grp = 0; c_grp < BLK_CH_OUT; c_grp = c_grp + 1) begin
                for (i = 0; i < 16; i = i + 1) dma_wdata[i*16 +: 16] = f_Bconv[c_grp*16+i];
                dma_write(2'd3, C_P1_BIAS + c_grp, dma_wdata);
                for (i = 0; i < 16; i = i + 1) dma_wdata[i*16 +: 16] = f_Inc_Scale[c_grp*16+i];
                dma_write(2'd3, C_INC_SCALE + c_grp, dma_wdata);
                for (i = 0; i < 16; i = i + 1) dma_wdata[i*16 +: 16] = f_Inc_Shift[c_grp*16+i];
                dma_write(2'd3, C_INC_SHIFT + c_grp, dma_wdata);
            end

            // -- Bot/B1 (dim×d_out)
            for (c_grp_br = 0; c_grp_br < (BLK_CH_OUT >= 8 ? 2 : 1); c_grp_br = c_grp_br + 1)
                for (c = 0; c < BLK_CH_OUT*16; c = c + 1) begin
                    for (i = 0; i < 16; i = i + 1)
                        dma_wdata[i*16 +: 16] = f_Wbot[(c_grp_br*16+i)*(BLK_CH_OUT*16)+c];
                    dma_write(2'd2, DW_BOT + c_grp_br*(BLK_CH_OUT*16) + c, dma_wdata);
                end
            for (c_grp_br = 0; c_grp_br < (BLK_CH_OUT >= 8 ? 2 : 1); c_grp_br = c_grp_br + 1)
                for (c = 0; c < BLK_CH_OUT*16; c = c + 1) begin
                    for (i = 0; i < 16; i = i + 1)
                        dma_wdata[i*16 +: 16] = f_Wb1[(c_grp_br*16+i)*(BLK_CH_OUT*16)+c];
                    dma_write(2'd2, DW_B1 + c_grp_br*(BLK_CH_OUT*16) + c, dma_wdata);
                end
            // -- B2/B3/B4 (dim×dim)
            for (c_grp_br = 0; c_grp_br < (BLK_CH_OUT >= 8 ? 2 : 1); c_grp_br = c_grp_br + 1)
                for (k = 0; k < 9; k = k + 1)
                    for (c = 0; c < BLK_CH_OUT*4; c = c + 1) begin
                        for (i = 0; i < 16; i = i + 1)
                            dma_wdata[i*16 +: 16] = f_Wb2[(c_grp_br*16+i)*(BLK_CH_OUT*4)*9 + c*9 + k];
                        dma_write(2'd2, DW_B2 + c_grp_br*9*(BLK_CH_OUT*4) + k*(BLK_CH_OUT*4) + c, dma_wdata);
                    end
            for (c_grp_br = 0; c_grp_br < (BLK_CH_OUT >= 8 ? 2 : 1); c_grp_br = c_grp_br + 1)
                for (k = 0; k < 19; k = k + 1)
                    for (c = 0; c < BLK_CH_OUT*4; c = c + 1) begin
                        for (i = 0; i < 16; i = i + 1)
                            dma_wdata[i*16 +: 16] = f_Wb3[(c_grp_br*16+i)*(BLK_CH_OUT*4)*19 + c*19 + k];
                        dma_write(2'd2, DW_B3 + c_grp_br*19*(BLK_CH_OUT*4) + k*(BLK_CH_OUT*4) + c, dma_wdata);
                    end
            for (c_grp_br = 0; c_grp_br < (BLK_CH_OUT >= 8 ? 2 : 1); c_grp_br = c_grp_br + 1)
                for (k = 0; k < 39; k = k + 1)
                    for (c = 0; c < BLK_CH_OUT*4; c = c + 1) begin
                        for (i = 0; i < 16; i = i + 1)
                            dma_wdata[i*16 +: 16] = f_Wb4[(c_grp_br*16+i)*(BLK_CH_OUT*4)*39 + c*39 + k];
                        dma_write(2'd2, DW_B4 + c_grp_br*39*(BLK_CH_OUT*4) + k*(BLK_CH_OUT*4) + c, dma_wdata);
                    end

            // -- Mamba in_proj X / Z
            for (c_grp_m = 0; c_grp_m < BLK_CH_M; c_grp_m = c_grp_m + 1)
                for (c = 0; c < BLK_CH_OUT*16; c = c + 1) begin
                    for (i = 0; i < 16; i = i + 1)
                        dma_wdata[i*16 +: 16] = f_Wmx[(c_grp_m*16+i)*(BLK_CH_OUT*16)+c];
                    dma_write(2'd2, DW_MX + c_grp_m*(BLK_CH_OUT*16) + c, dma_wdata);
                end
            for (c_grp_m = 0; c_grp_m < BLK_CH_M; c_grp_m = c_grp_m + 1)
                for (c = 0; c < BLK_CH_OUT*16; c = c + 1) begin
                    for (i = 0; i < 16; i = i + 1)
                        dma_wdata[i*16 +: 16] = f_Wmz[(c_grp_m*16+i)*(BLK_CH_OUT*16)+c];
                    dma_write(2'd2, DW_MZ + c_grp_m*(BLK_CH_OUT*16) + c, dma_wdata);
                end

            // -- Depthwise conv weight + bias
            for (c_grp_m = 0; c_grp_m < BLK_CH_M; c_grp_m = c_grp_m + 1) begin
                for (k = 0; k < 4; k = k + 1) begin
                    for (i = 0; i < 16; i = i + 1)
                        dma_wdata[i*16 +: 16] = f_Wconv[(c_grp_m*16+i)*4+k];
                    dma_write(2'd2, DW_DW + c_grp_m*4 + k, dma_wdata);
                end
                for (i = 0; i < 16; i = i + 1) dma_wdata[i*16 +: 16] = f_Bconv_dw[c_grp_m*16+i];
                dma_write(2'd3, C_M_DW_BIAS + c_grp_m, dma_wdata);
            end

            // -- X_proj
            for (c_grp = 0; c_grp < 3; c_grp = c_grp + 1)
                for (c = 0; c < BLK_D_INNER; c = c + 1) begin
                    for (i = 0; i < 16; i = i + 1)
                        dma_wdata[i*16 +: 16] = f_Wxproj[(c_grp*16+i)*BLK_D_INNER+c];
                    dma_write(2'd2, DW_XPROJ + c_grp*BLK_D_INNER + c, dma_wdata);
                end

            // -- Dt_proj + bias
            for (c_grp_m = 0; c_grp_m < BLK_CH_M; c_grp_m = c_grp_m + 1) begin
                for (k = 0; k < BLK_DT_RANK; k = k + 1) begin
                    for (i = 0; i < 16; i = i + 1)
                        dma_wdata[i*16 +: 16] = f_Wdt[(c_grp_m*16+i)*BLK_DT_RANK+k];
                    dma_write(2'd2, DW_DTPROJ + c_grp_m*BLK_DT_RANK + k, dma_wdata);
                end
                for (i = 0; i < 16; i = i + 1) dma_wdata[i*16 +: 16] = f_Bdt[c_grp_m*16+i];
                dma_write(2'd3, C_M_DT_BIAS + c_grp_m, dma_wdata);
            end

            // -- A_signed
            for (c_grp_m = 0; c_grp_m < BLK_CH_M; c_grp_m = c_grp_m + 1)
                for (k = 0; k < 16; k = k + 1) begin
                    for (i = 0; i < 16; i = i + 1)
                        dma_wdata[i*16 +: 16] = f_Alog[(c_grp_m*16+i)*16+k];
                    dma_write(2'd2, DW_ALOG + c_grp_m*16 + k, dma_wdata);
                end

            // -- D_param
            for (c_grp_m = 0; c_grp_m < BLK_CH_M; c_grp_m = c_grp_m + 1) begin
                for (i = 0; i < 16; i = i + 1) dma_wdata[i*16 +: 16] = f_Dparam[c_grp_m*16+i];
                dma_write(2'd2, DW_DPARAM + c_grp_m, dma_wdata);
            end

            // -- OutProj
            for (c_grp = 0; c_grp < BLK_CH_OUT; c_grp = c_grp + 1)
                for (c = 0; c < BLK_D_INNER; c = c + 1) begin
                    for (i = 0; i < 16; i = i + 1)
                        dma_wdata[i*16 +: 16] = f_Woutproj[(c_grp*16+i)*BLK_D_INNER+c];
                    dma_write(2'd2, DW_OUTPROJ + c_grp*BLK_D_INNER + c, dma_wdata);
                end

            // -- RMSNorm gamma
            for (c_grp = 0; c_grp < BLK_CH_OUT; c_grp = c_grp + 1) begin
                for (i = 0; i < 16; i = i + 1) dma_wdata[i*16 +: 16] = f_Norm_W[c_grp*16+i];
                dma_write(2'd3, C_NORM_W + c_grp, dma_wdata);
            end
        end
    endtask

    // ================================================================
    // task readmemh_block — load all weight + scale/shift files for a
    // given block.  Per-block goldens live under
    //   golden_all/block_{XX}_layer{YY}/...
    //
    // Block index → directory mapping (from itmn_pipeline.py output):
    //   block 0 → block_00_layer00
    //   block 1 → block_01_layer01
    //   block 2 → block_02_layer03
    //   block 3 → block_03_layer04
    //   block 4 → block_04_layer06
    // ================================================================
    task readmemh_block;
        input integer bid;
        begin
            case (bid)
            0: begin
                $readmemh("golden_all/block_00_layer00/P1_Weight_Fused.txt",    f_Wp1);
                $readmemh("golden_all/block_00_layer00/P1_Bias_Fused.txt",      f_Bconv);
                $readmemh("golden_all/block_00_layer00/W_Bot.txt",              f_Wbot);
                $readmemh("golden_all/block_00_layer00/W_B1.txt",               f_Wb1);
                $readmemh("golden_all/block_00_layer00/W_B2.txt",               f_Wb2);
                $readmemh("golden_all/block_00_layer00/W_B3.txt",               f_Wb3);
                $readmemh("golden_all/block_00_layer00/W_B4.txt",               f_Wb4);
                $readmemh("golden_all/block_00_layer00/Inc_BN_Scale.txt",       f_Inc_Scale);
                $readmemh("golden_all/block_00_layer00/Inc_BN_Shift.txt",       f_Inc_Shift);
                $readmemh("golden_all/block_00_layer00/Mam_W_InProj_X.txt",     f_Wmx);
                $readmemh("golden_all/block_00_layer00/Mam_W_InProj_Z.txt",     f_Wmz);
                $readmemh("golden_all/block_00_layer00/Mam_W_Conv.txt",         f_Wconv);
                $readmemh("golden_all/block_00_layer00/Mam_B_Conv.txt",         f_Bconv_dw);
                $readmemh("golden_all/block_00_layer00/Mam_W_XProj.txt",        f_Wxproj);
                $readmemh("golden_all/block_00_layer00/Mam_W_DtProj.txt",       f_Wdt);
                $readmemh("golden_all/block_00_layer00/Mam_B_DtProj.txt",       f_Bdt);
                $readmemh("golden_all/block_00_layer00/Mam_A_signed.txt",       f_Alog);
                $readmemh("golden_all/block_00_layer00/Mam_D_param.txt",        f_Dparam);
                $readmemh("golden_all/block_00_layer00/Mam_W_OutProj.txt",      f_Woutproj);
                $readmemh("golden_all/block_00_layer00/Mam_W_Norm.txt",         f_Norm_W);
            end
            1: begin
                $readmemh("golden_all/block_01_layer01/P1_Weight_Fused.txt",    f_Wp1);
                $readmemh("golden_all/block_01_layer01/P1_Bias_Fused.txt",      f_Bconv);
                $readmemh("golden_all/block_01_layer01/W_Bot.txt",              f_Wbot);
                $readmemh("golden_all/block_01_layer01/W_B1.txt",               f_Wb1);
                $readmemh("golden_all/block_01_layer01/W_B2.txt",               f_Wb2);
                $readmemh("golden_all/block_01_layer01/W_B3.txt",               f_Wb3);
                $readmemh("golden_all/block_01_layer01/W_B4.txt",               f_Wb4);
                $readmemh("golden_all/block_01_layer01/Inc_BN_Scale.txt",       f_Inc_Scale);
                $readmemh("golden_all/block_01_layer01/Inc_BN_Shift.txt",       f_Inc_Shift);
                $readmemh("golden_all/block_01_layer01/Mam_W_InProj_X.txt",     f_Wmx);
                $readmemh("golden_all/block_01_layer01/Mam_W_InProj_Z.txt",     f_Wmz);
                $readmemh("golden_all/block_01_layer01/Mam_W_Conv.txt",         f_Wconv);
                $readmemh("golden_all/block_01_layer01/Mam_B_Conv.txt",         f_Bconv_dw);
                $readmemh("golden_all/block_01_layer01/Mam_W_XProj.txt",        f_Wxproj);
                $readmemh("golden_all/block_01_layer01/Mam_W_DtProj.txt",       f_Wdt);
                $readmemh("golden_all/block_01_layer01/Mam_B_DtProj.txt",       f_Bdt);
                $readmemh("golden_all/block_01_layer01/Mam_A_signed.txt",       f_Alog);
                $readmemh("golden_all/block_01_layer01/Mam_D_param.txt",        f_Dparam);
                $readmemh("golden_all/block_01_layer01/Mam_W_OutProj.txt",      f_Woutproj);
                $readmemh("golden_all/block_01_layer01/Mam_W_Norm.txt",         f_Norm_W);
            end
            2: begin
                $readmemh("golden_all/block_02_layer03/P1_Weight_Fused.txt",    f_Wp1);
                $readmemh("golden_all/block_02_layer03/P1_Bias_Fused.txt",      f_Bconv);
                $readmemh("golden_all/block_02_layer03/W_Bot.txt",              f_Wbot);
                $readmemh("golden_all/block_02_layer03/W_B1.txt",               f_Wb1);
                $readmemh("golden_all/block_02_layer03/W_B2.txt",               f_Wb2);
                $readmemh("golden_all/block_02_layer03/W_B3.txt",               f_Wb3);
                $readmemh("golden_all/block_02_layer03/W_B4.txt",               f_Wb4);
                $readmemh("golden_all/block_02_layer03/Inc_BN_Scale.txt",       f_Inc_Scale);
                $readmemh("golden_all/block_02_layer03/Inc_BN_Shift.txt",       f_Inc_Shift);
                $readmemh("golden_all/block_02_layer03/Mam_W_InProj_X.txt",     f_Wmx);
                $readmemh("golden_all/block_02_layer03/Mam_W_InProj_Z.txt",     f_Wmz);
                $readmemh("golden_all/block_02_layer03/Mam_W_Conv.txt",         f_Wconv);
                $readmemh("golden_all/block_02_layer03/Mam_B_Conv.txt",         f_Bconv_dw);
                $readmemh("golden_all/block_02_layer03/Mam_W_XProj.txt",        f_Wxproj);
                $readmemh("golden_all/block_02_layer03/Mam_W_DtProj.txt",       f_Wdt);
                $readmemh("golden_all/block_02_layer03/Mam_B_DtProj.txt",       f_Bdt);
                $readmemh("golden_all/block_02_layer03/Mam_A_signed.txt",       f_Alog);
                $readmemh("golden_all/block_02_layer03/Mam_D_param.txt",        f_Dparam);
                $readmemh("golden_all/block_02_layer03/Mam_W_OutProj.txt",      f_Woutproj);
                $readmemh("golden_all/block_02_layer03/Mam_W_Norm.txt",         f_Norm_W);
            end
            3: begin
                $readmemh("golden_all/block_03_layer04/P1_Weight_Fused.txt",    f_Wp1);
                $readmemh("golden_all/block_03_layer04/P1_Bias_Fused.txt",      f_Bconv);
                $readmemh("golden_all/block_03_layer04/W_Bot.txt",              f_Wbot);
                $readmemh("golden_all/block_03_layer04/W_B1.txt",               f_Wb1);
                $readmemh("golden_all/block_03_layer04/W_B2.txt",               f_Wb2);
                $readmemh("golden_all/block_03_layer04/W_B3.txt",               f_Wb3);
                $readmemh("golden_all/block_03_layer04/W_B4.txt",               f_Wb4);
                $readmemh("golden_all/block_03_layer04/Inc_BN_Scale.txt",       f_Inc_Scale);
                $readmemh("golden_all/block_03_layer04/Inc_BN_Shift.txt",       f_Inc_Shift);
                $readmemh("golden_all/block_03_layer04/Mam_W_InProj_X.txt",     f_Wmx);
                $readmemh("golden_all/block_03_layer04/Mam_W_InProj_Z.txt",     f_Wmz);
                $readmemh("golden_all/block_03_layer04/Mam_W_Conv.txt",         f_Wconv);
                $readmemh("golden_all/block_03_layer04/Mam_B_Conv.txt",         f_Bconv_dw);
                $readmemh("golden_all/block_03_layer04/Mam_W_XProj.txt",        f_Wxproj);
                $readmemh("golden_all/block_03_layer04/Mam_W_DtProj.txt",       f_Wdt);
                $readmemh("golden_all/block_03_layer04/Mam_B_DtProj.txt",       f_Bdt);
                $readmemh("golden_all/block_03_layer04/Mam_A_signed.txt",       f_Alog);
                $readmemh("golden_all/block_03_layer04/Mam_D_param.txt",        f_Dparam);
                $readmemh("golden_all/block_03_layer04/Mam_W_OutProj.txt",      f_Woutproj);
                $readmemh("golden_all/block_03_layer04/Mam_W_Norm.txt",         f_Norm_W);
            end
            4: begin
                $readmemh("golden_all/block_04_layer06/P1_Weight_Fused.txt",    f_Wp1);
                $readmemh("golden_all/block_04_layer06/P1_Bias_Fused.txt",      f_Bconv);
                $readmemh("golden_all/block_04_layer06/W_Bot.txt",              f_Wbot);
                $readmemh("golden_all/block_04_layer06/W_B1.txt",               f_Wb1);
                $readmemh("golden_all/block_04_layer06/W_B2.txt",               f_Wb2);
                $readmemh("golden_all/block_04_layer06/W_B3.txt",               f_Wb3);
                $readmemh("golden_all/block_04_layer06/W_B4.txt",               f_Wb4);
                $readmemh("golden_all/block_04_layer06/Inc_BN_Scale.txt",       f_Inc_Scale);
                $readmemh("golden_all/block_04_layer06/Inc_BN_Shift.txt",       f_Inc_Shift);
                $readmemh("golden_all/block_04_layer06/Mam_W_InProj_X.txt",     f_Wmx);
                $readmemh("golden_all/block_04_layer06/Mam_W_InProj_Z.txt",     f_Wmz);
                $readmemh("golden_all/block_04_layer06/Mam_W_Conv.txt",         f_Wconv);
                $readmemh("golden_all/block_04_layer06/Mam_B_Conv.txt",         f_Bconv_dw);
                $readmemh("golden_all/block_04_layer06/Mam_W_XProj.txt",        f_Wxproj);
                $readmemh("golden_all/block_04_layer06/Mam_W_DtProj.txt",       f_Wdt);
                $readmemh("golden_all/block_04_layer06/Mam_B_DtProj.txt",       f_Bdt);
                $readmemh("golden_all/block_04_layer06/Mam_A_signed.txt",       f_Alog);
                $readmemh("golden_all/block_04_layer06/Mam_D_param.txt",        f_Dparam);
                $readmemh("golden_all/block_04_layer06/Mam_W_OutProj.txt",      f_Woutproj);
                $readmemh("golden_all/block_04_layer06/Mam_W_Norm.txt",         f_Norm_W);
            end
            endcase
        end
    endtask

    // ================================================================
    // task run_block — pulse start, wait done_all (or done_fc for block 4)
    // ================================================================
    task run_block;
        input integer bid;
        begin
            @(negedge clk); start = 1;
            @(posedge clk); #1;
            @(negedge clk); start = 0;
            repeat(3) @(posedge clk);

            cycle_blk = 0;
            if (bid == 4) begin
                // Block 4: head_mode=1, terminates via done_fc → done_all
                while (!uut.done_fc && cycle_blk < MAX_CYCLES) begin
                    @(posedge clk); cycle_blk = cycle_blk + 1;
                    if (cycle_blk % 2000000 == 0)
                        $display("        [BLK %0d sample %0d] %0dM cyc, state=%0d",
                                 bid, sample_idx, cycle_blk/1000000, uut.state);
                end
            end else begin
                while (!uut.done_all && cycle_blk < MAX_CYCLES) begin
                    @(posedge clk); cycle_blk = cycle_blk + 1;
                    if (cycle_blk % 2000000 == 0)
                        $display("        [BLK %0d sample %0d] %0dM cyc, state=%0d",
                                 bid, sample_idx, cycle_blk/1000000, uut.state);
                end
            end
            if (cycle_blk >= MAX_CYCLES)
                $display("    [WARN] block %0d sample %0d TIMEOUT after %0d cycles",
                         bid, sample_idx, cycle_blk);
            repeat(5) @(posedge clk);
        end
    endtask

    // ================================================================
    // task run_one_sample — full end-to-end pass for sample_idx
    // ================================================================
    task run_one_sample;
        input integer sidx;
        begin
            $display("\n--[sample %0d]----------------------------------------------------", sidx);

            // 1. DMA load raw waveform → ram_b[B_ENC_IN_BASE..+999]
            load_waveform_sample(sidx);

            // 2. Block 0 (encoder + block-0 ITM chain, cascade copy to next)
            blk = 0; set_block_params(blk);
            readmemh_block(blk);
            load_block_weights;
            run_block(blk);

            // 3-5. Block 1..3 (no encoder, cascade with pool/copy alternating)
            for (blk = 1; blk < 4; blk = blk + 1) begin
                set_block_params(blk);
                readmemh_block(blk);
                load_block_weights;
                run_block(blk);
            end

            // 6. Block 4 (terminal, head_mode=1 → GAP + FC → logit0..4)
            blk = 4; set_block_params(blk);
            readmemh_block(blk);
            load_block_weights;
            run_block(blk);

            // 7. Compare logits
            got_l0 = logit0; got_l1 = logit1; got_l2 = logit2;
            got_l3 = logit3; got_l4 = logit4;
            exp_l0 = f_AllLogits[sidx*5 + 0];
            exp_l1 = f_AllLogits[sidx*5 + 1];
            exp_l2 = f_AllLogits[sidx*5 + 2];
            exp_l3 = f_AllLogits[sidx*5 + 3];
            exp_l4 = f_AllLogits[sidx*5 + 4];

            // HW predicted class = argmax(got_l0..got_l4)
            max_v = got_l0; pred_hw = 0;
            if (got_l1 > max_v) begin max_v = got_l1; pred_hw = 1; end
            if (got_l2 > max_v) begin max_v = got_l2; pred_hw = 2; end
            if (got_l3 > max_v) begin max_v = got_l3; pred_hw = 3; end
            if (got_l4 > max_v) begin max_v = got_l4; pred_hw = 4; end

            // Expected (Python integer golden) predicted class = argmax(exp_l0..exp_l4)
            max_v = exp_l0; pred_exp = 0;
            if (exp_l1 > max_v) begin max_v = exp_l1; pred_exp = 1; end
            if (exp_l2 > max_v) begin max_v = exp_l2; pred_exp = 2; end
            if (exp_l3 > max_v) begin max_v = exp_l3; pred_exp = 3; end
            if (exp_l4 > max_v) begin max_v = exp_l4; pred_exp = 4; end

            // Float-model predicted class (from PyTorch forward pass; written by extract_multi.py)
            pred_float = f_AllPredFloat[sidx];

            // Byte-exact match (each logit must equal expected, signed)
            logit_match =
                (got_l0 == exp_l0) && (got_l1 == exp_l1) && (got_l2 == exp_l2) &&
                (got_l3 == exp_l3) && (got_l4 == exp_l4);

            // Max absolute diff (for reporting near-miss)
            max_diff = 0;
            if ($signed(got_l0 - exp_l0) > max_diff)  max_diff = $signed(got_l0 - exp_l0);
            if ($signed(exp_l0 - got_l0) > max_diff)  max_diff = $signed(exp_l0 - got_l0);
            if ($signed(got_l1 - exp_l1) > max_diff)  max_diff = $signed(got_l1 - exp_l1);
            if ($signed(exp_l1 - got_l1) > max_diff)  max_diff = $signed(exp_l1 - got_l1);
            if ($signed(got_l2 - exp_l2) > max_diff)  max_diff = $signed(got_l2 - exp_l2);
            if ($signed(exp_l2 - got_l2) > max_diff)  max_diff = $signed(exp_l2 - got_l2);
            if ($signed(got_l3 - exp_l3) > max_diff)  max_diff = $signed(got_l3 - exp_l3);
            if ($signed(exp_l3 - got_l3) > max_diff)  max_diff = $signed(exp_l3 - got_l3);
            if ($signed(got_l4 - exp_l4) > max_diff)  max_diff = $signed(got_l4 - exp_l4);
            if ($signed(exp_l4 - got_l4) > max_diff)  max_diff = $signed(exp_l4 - got_l4);

            if (logit_match)                    match_cnt            = match_cnt + 1;
            if (pred_hw  == pred_exp)           match_pred_hw_exp    = match_pred_hw_exp + 1;
            if (pred_hw  == pred_float)         match_pred_hw_float  = match_pred_hw_float + 1;
            if (pred_exp == pred_float)         match_pred_exp_float = match_pred_exp_float + 1;
            total_samples = total_samples + 1;

            $display("  HW    logits = [%6d, %6d, %6d, %6d, %6d] -> class %0d",
                     got_l0, got_l1, got_l2, got_l3, got_l4, pred_hw);
            $display("  EXP   logits = [%6d, %6d, %6d, %6d, %6d] -> class %0d",
                     exp_l0, exp_l1, exp_l2, exp_l3, exp_l4, pred_exp);
            $display("  FLOAT model predicted class = %0d", pred_float);
            $display("  byte-exact(HW vs EXP)=%s  max|diff|=%0d",
                     logit_match ? "PASS" : "FAIL", max_diff);
            $display("  pred-match  HW-vs-EXP=%s  HW-vs-FLOAT=%s  EXP-vs-FLOAT=%s",
                     (pred_hw  == pred_exp)   ? "YES" : "NO",
                     (pred_hw  == pred_float) ? "YES" : "NO",
                     (pred_exp == pred_float) ? "YES" : "NO");
            $display("  [running: byte-exact %0d/%0d  HW-vs-EXP %0d/%0d  HW-vs-FLOAT %0d/%0d]",
                     match_cnt, total_samples,
                     match_pred_hw_exp, total_samples,
                     match_pred_hw_float, total_samples);
        end
    endtask

    // ================================================================
    // MAIN
    // ================================================================
    initial begin
        $display("================================================================");
        $display("  ITMN_TB_V2 -- end-to-end (encoder + 5 ITM + GAP + FC)");
        $display("  FRAC_BITS=%0d  NUM_SAMPLES=%0d  MAX_CYCLES=%0d",
                 `FRAC_BITS, NUM_SAMPLES, MAX_CYCLES);
        $display("================================================================");

        dma_write_en=0; dma_target=0; dma_addr=0; dma_wdata=0; start=0;
        match_cnt = 0; total_samples = 0;
        match_pred_hw_exp    = 0;
        match_pred_hw_float  = 0;
        match_pred_exp_float = 0;

        // ---- Reset ----
        rst = 1; repeat(5) @(posedge clk); #1;
        rst = 0; repeat(3) @(posedge clk); #1;

        // ---- Load persistent file data ----
        $display(">> $readmemh encoder + FC + multi-sample data...");
        $readmemh("golden_all/encoder/Encoder_Weight_Fused.txt", f_EncW);
        $readmemh("golden_all/encoder/Encoder_Bias_Fused.txt",   f_EncB);
        $readmemh("golden_all/gap_fc/FC_Weight.txt",             f_FcW);
        $readmemh("golden_all/gap_fc/FC_Bias.txt",               f_FcB);
        $readmemh("golden_all/multi/all_waves.txt",              f_AllWaves);
        $readmemh("golden_all/multi/all_logits.txt",             f_AllLogits);
        $readmemh("golden_all/multi/all_pred_float.txt",         f_AllPredFloat);

        // ---- DMA-load encoder + FC constants once (persistent in ram_weight/ram_const) ----
        $display(">> DMA loading encoder + FC weights/bias (boot-once)...");
        load_encoder_and_fc_constants;
        $display("   Encoder + FC constants loaded.");

        // ---- Main sample loop ----
        for (sample_idx = 0; sample_idx < NUM_SAMPLES; sample_idx = sample_idx + 1) begin
            run_one_sample(sample_idx);
        end

        // ---- Final summary ----
        $display("\n================================================================");
        $display("  FINAL SUMMARY  (%0d samples)", total_samples);
        $display("  ----------------------------------------------------------------");
        $display("  byte-exact (HW vs EXP)  : %0d/%0d  (%0d%%)",
                 match_cnt, total_samples,
                 (total_samples > 0) ? (100*match_cnt/total_samples) : 0);
        $display("  pred-match HW vs EXP    : %0d/%0d  (%0d%%)",
                 match_pred_hw_exp, total_samples,
                 (total_samples > 0) ? (100*match_pred_hw_exp/total_samples) : 0);
        $display("  pred-match HW vs FLOAT  : %0d/%0d  (%0d%%)",
                 match_pred_hw_float, total_samples,
                 (total_samples > 0) ? (100*match_pred_hw_float/total_samples) : 0);
        $display("  pred-match EXP vs FLOAT : %0d/%0d  (%0d%%)  (sanity: should equal HW-vs-FLOAT)",
                 match_pred_exp_float, total_samples,
                 (total_samples > 0) ? (100*match_pred_exp_float/total_samples) : 0);
        $display("================================================================");
        $finish;
    end

endmodule
